name: 'Setup Docker on Ubuntu'
description: 'Install Docker on Ubuntu Actions Runner'
inputs:
  add-to-group:
    description: 'Signifies if the user should be added to the Docker group'
    required: true
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Update APT Repository
      run: sudo apt-get update
      shell: bash
    - name: Install Docker and Compose
      run: sudo apt-get install -y docker.io docker-compose
      shell: bash
    - name: Configure Docker Group
      if: ${{ inputs.add-to-group == 'true' }}
      shell: bash
      run: sudo usermod -aG docker $(whoami) && newgrp docker
    - name: Validate Docker Installation
      run: docker run --rm hello-world
      shell: bash
