name: 'Setup Docker'
description: 'Install Docker on Actions Runner'
runs:
  using: "composite"
  steps:
    - run: sudo get-docker.sh
      shell: bash
    - run: sudo usermod -aG docker $USER
      shell: bash
    - run: newgrp docker
      shell: bash          
    - run: docker --rm hello-world
      shell: bash