name: 'Setup Docker on Ubuntu'
description: 'Install Docker on Ubuntu Actions Runner'
runs:
  using: "composite"
  steps:
    - run: sudo apt-get update
      shell: bash
    - run: sudo apt-get install -y docker.io docker-compose
      shell: bash
    - run: docker --rm hello-world
      shell: bash
